---
title: "IDDAP: Infectious Diseases Data Analysis Program"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
    social: menu
    theme: yeti
---

```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(mgcv)
library(shiny)
library(dplyr)
library(readr)
#newdata<-read_csv('mdata.csv')

```

Inputs {.sidebar data-width=350}
-----------------------------------------------------------------------
### File Upload {data-height=100}
```{r}
fileInput('file1', h5('Choose a file to upload'),
            accept = c('text/csv','text/comma-separated-values',
                       'text/tab-separated-values','text/plain','.csv','.tsv'))


```

-----------------------------------------------------------------------
### Sorting Criteria {data-height=700}
```{r}

sliderInput('age', "Age Range", min = 0, max = 110, value=c(0, 110) )


```

Column {data-width=250}
-----------------------------------------------------------------------
### Sorting Criteria {data-height=100}
```{r}



```
### Patient Data Output {data-height=500}

```{r}
renderTable({
  if(is.null(input$file1))
    return()
  newdata<-read_csv(input$file1$datapath)
  assign('inputfile',newdata)
  #do things to modify the "input file" below here"
  
})


```

### Data Analytics  {data-height=200}

```{r}

```

