---
title: "IDDAP: Infectious Diseases Data Analysis Program"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
    social: menu
    theme: yeti
#hello this is my comment by Mike
---
```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(mgcv)
library(shiny)
library(dplyr)
library(readr)
```


Inputs {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}
fileInput('file1', h5('Choose a file to upload'),
            accept = c('text/csv','text/comma-separated-values',
                       'text/tab-separated-values','text/plain','.csv','.tsv'))
sliderInput('age', "Age Range", min = 0, max = 110, value=c(0, 110) )
sliderInput('weight', "Weight Range (kgs) ", min = 0, max = 150, value=c(0, 150))
sliderInput('height', "Height Range (m) ", min = 0, max = 2.5, value=c(0, 2.5))
dateRangeInput('OPATad', "Admittance to the OPAT Program", start= "2005-01-01",end= "2020-01-01", min = "2005-01-01", max ="2020-01-01", startview="year")
checkboxGroupInput("resis", "Resistant Infection? (deselection will filter out the option)", choices= c("Yes"=1, "No"=2), selected = c(1,2))
checkboxGroupInput("riskofre", "High Risk of Readmission? (deselection will filter out the option)", choices= c("Yes"=1, "No"=2), selected = c(1,2))
checkboxGroupInput("MF", "Gender: (deselection will filter out the option)", choices= c("Male", "Female"), selected = c("Male", "Female"))
checkboxGroupInput("AB", "Antibiotic Type: (deselection will filter out the option)", choices= c("Erythromycin"=1, "Lymecycline"=2, "Norfloxacin"=3, "Ciprofloxacin"=4, "Amoxicillin"=5, 	"Gentamicin"=6,"Phenoxymethylpenicillin"=7, "Other"=8), selected = c(1, 2, 3, 4, 5, 6, 7, 8))

```

Column {data-width=250}
-----------------------------------------------------------------------
### Sorting Criteria {data-height=100}
```{r}

```
### Patient Data Output {data-height=500}

```{r}
library(knitr)

renderTable({
  # if(is.null(input$file1))
  #   return()
  newdata<-read_csv('mdata.csv')
  # ^(input$file1$datapath) for when you want it to be the file uploaded
  assign('inputfile',newdata)
  #do things to modify the "input file" below here"
  
  # Age input conditionals
  inputfile<- filter(inputfile,`Age`>=as.numeric(input$age[1]))
  inputfile<- filter(inputfile,`Age`<=as.numeric(input$age[2]))
  # Weight input conditionals
  inputfile<- filter(inputfile,`Weight (kgs)`>=as.numeric(input$weight[1]))
  inputfile<- filter(inputfile,`Weight (kgs)`<=as.numeric(input$weight[2]))  
  # # Height input conditionals
  inputfile<- filter(inputfile,`Height (m)`>=as.numeric(input$height[1]))
  inputfile<- filter(inputfile,`Height (m)`<=as.numeric(input$height[2]))
  # Date input conditionals
  # inputfile<- filter(inputfile, as.Date.character(`OPAT Start Date`,"%m/%d/%y") >= format(input$OPATad[1], "%m/%d/%y"))
  # inputfile<- filter(inputfile, as.Date.character(`OPAT Start Date`, "%m/%d/%y")<= format(input$OPATad[2], "%m/%d/%y"))
  # Risk of readmission checkbox group
  if("1" %in% input$riskofre==FALSE )
    inputfile<- filter(inputfile,`High Risk of Readmission`=='N')
  if("2" %in% input$riskofre==FALSE )
    inputfile<- filter(inputfile,`High Risk of Readmission`=='Y')
  if(is.null(input$riskofre))
    inputfile <- "please mark whether the patient is at risk for readmission"
  
  # Resistant Checkbox Group conditionals
  if("1" %in% input$resis==FALSE )
    inputfile<- filter(inputfile,`Resistant Organism (Y/N)`=='N')
  if("2" %in% input$resis==FALSE )
    inputfile<- filter(inputfile,`Resistant Organism (Y/N)`=='Y')
  if(is.null(input$resis))
    inputfile <- "please select a resistance"
  
  # Antibiotic Type Checkbox Group conditionals
  if("1" %in% input$AB==FALSE )
    inputfile<- filter(inputfile,`Antibiotic`!='erythromycin')
  if("2" %in% input$AB==FALSE )
    inputfile<- filter(inputfile,`Antibiotic`!='lymecycline')
  if("3" %in% input$AB==FALSE )
    inputfile<- filter(inputfile,`Antibiotic`!='norfloxacin')
  if("4" %in% input$AB==FALSE )
    inputfile<- filter(inputfile,`Antibiotic`!='ciprofloxacin')
  if("5" %in% input$AB==FALSE )
    inputfile<- filter(inputfile,`Antibiotic`!='amoxicillin')
  if("6" %in% input$AB==FALSE )
    inputfile<- filter(inputfile,`Antibiotic`!='gentamicin')
  if("7" %in% input$AB==FALSE )
    inputfile<- filter(inputfile,`Antibiotic`!='phenoxymethylpenicillin')
  if(is.null(input$AB))
    inputfile <- "please select an antibiotic type"
  # needed at the very end to return the modified inputful
  inputfile
})
```

### Data Analytics  {data-height=200}

```{r}

```

